In [15]:
from google.cloud import bigquery
import pandas as pd


client = bigquery.Client(project='datenglea')

# Define the dataset and table name
dataset_id = 'H1BData'
table_id = 'H1practisetable'  # Replace with your desired table name

# Define the schema for the table
schema = [
    bigquery.SchemaField('Record', 'INT64'),  # Rename 'Unnamed: 0' to 'id'
    bigquery.SchemaField('CASE_STATUS', 'STRING'),
    bigquery.SchemaField('EMPLOYER_NAME', 'STRING'),
    bigquery.SchemaField('SOC_NAME', 'STRING'),
    bigquery.SchemaField('JOB_TITLE', 'STRING'),
    bigquery.SchemaField('FULL_TIME_POSITION', 'STRING'),
    bigquery.SchemaField('PREVAILING_WAGE', 'FLOAT64'),  # Assuming numeric values
    bigquery.SchemaField('YEAR', 'INT64'),
    bigquery.SchemaField('WORKSITE', 'STRING'),
    bigquery.SchemaField('lon', 'FLOAT64'),
    bigquery.SchemaField('lat', 'FLOAT64'),
]


# Define the table reference
table_ref = client.dataset(dataset_id).table(table_id)

# Create the table
table = bigquery.Table(table_ref, schema=schema)
table = client.create_table(table)

print(f'Table {table_id} created in dataset {dataset_id}.')

Table H1practisetable created in dataset H1BData.

In [16]:
from google.cloud import bigquery
import pandas as pd

# Initialize BigQuery client
client = bigquery.Client(project='datenglea')

# Define the dataset and table
dataset_id = 'datenglea.H1BData'
table_id = 'H1practisetable'

# Path to your CSV file in GCS
csv_file_path = 'gs://cloudstoragedat/Raw Data File/h1b_kaggle_data.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)

# Display the DataFrame to check how it looks
print(df.head())

   Unnamed: 0          CASE_STATUS  \
0           1  CERTIFIED-WITHDRAWN
1           2  CERTIFIED-WITHDRAWN
2           3  CERTIFIED-WITHDRAWN
3           4  CERTIFIED-WITHDRAWN
4           5            WITHDRAWN

                                       EMPLOYER_NAME  \
0                             UNIVERSITY OF MICHIGAN
1                             GOODMAN NETWORKS, INC.
2                          PORTS AMERICA GROUP, INC.
3  GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...
4                          PEABODY INVESTMENTS CORP.

                        SOC_NAME                     JOB_TITLE  \
0  BIOCHEMISTS AND BIOPHYSICISTS  POSTDOCTORAL RESEARCH FELLOW
1               CHIEF EXECUTIVES       CHIEF OPERATING OFFICER
2               CHIEF EXECUTIVES         CHIEF PROCESS OFFICER
3               CHIEF EXECUTIVES   REGIONAL PRESIDEN, AMERICAS
4               CHIEF EXECUTIVES  PRESIDENT MONGOLIA AND INDIA

  FULL_TIME_POSITION  PREVAILING_WAGE    YEAR                 WORKSITE  \
0                  N          36067.0  2016.0      ANN ARBOR, MICHIGAN
1                  Y         242674.0  2016.0             PLANO, TEXAS
2                  Y         193066.0  2016.0  JERSEY CITY, NEW JERSEY
3                  Y         220314.0  2016.0         DENVER, COLORADO
4                  Y         157518.4  2016.0      ST. LOUIS, MISSOURI

          lon        lat
0  -83.743038  42.280826
1  -96.698886  33.019843
2  -74.077642  40.728158
3 -104.990251  39.739236
4  -90.199404  38.627003

In [17]:
df = df.rename(columns={'Unnamed: 0': 'record'})

In [18]:
df.head()

,record,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.0,2016.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.0,2016.0,"PLANO, TEXAS",-96.698886,33.019843
2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.0,2016.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.0,2016.0,"DENVER, COLORADO",-104.990251,39.739236
4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.4,2016.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003

In [28]:
from google.cloud import bigquery
import pandas as pd

# Initialize BigQuery client
client = bigquery.Client(project='datenglea')

# Define the dataset and table name
dataset_id = 'H1BData'
table_id = 'H1practisetable'

# Define the table reference
table_ref = client.dataset(dataset_id).table(table_id)

# Upload the DataFrame to BigQuery
job = client.load_table_from_dataframe(df, table_ref)

# Wait for the job to complete
job.result()

print(f'Data successfully written to {dataset_id}.{table_id}.')

Data successfully written to H1BData.H1practisetable.

In [38]:
from google.cloud import bigquery

# Initialize BigQuery client
client = bigquery.Client(project='datenglea')

# Define the table reference
dataset_id = 'H1BData'
table_id = 'H1practisetable'
table_ref = client.dataset(dataset_id).table(table_id)

# Run a query to count the number of rows in the table
query = f"SELECT COUNT(*) as record_count FROM `{dataset_id}.{table_id}`"
query_job = client.query(query)

display = f"SELECT *  FROM `{dataset_id}.{table_id}`LIMIT 10"
d_query_job = client.query(display)

for row in d_query_job.result():
    print(row)
# Get the results
results = query_job.result()

# Print the count
for row in results:
    print(f"Total records: {row.record_count}")

Row((1, 'CERTIFIED-WITHDRAWN', 'UNIVERSITY OF MICHIGAN', 'BIOCHEMISTS AND BIOPHYSICISTS', 'POSTDOCTORAL RESEARCH FELLOW', 'N', 36067.0, 2016, 'ANN ARBOR, MICHIGAN', -83.7430378, 42.2808256), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((4, 'CERTIFIED-WITHDRAWN', 'GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY OF TOMKINS PLC', 'CHIEF EXECUTIVES', 'REGIONAL PRESIDEN, AMERICAS', 'Y', 220314.0, 2016, 'DENVER, COLORADO', -104.990251, 39.7392358), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((5, 'WITHDRAWN', 'PEABODY INVESTMENTS CORP.', 'CHIEF EXECUTIVES', 'PRESIDENT MONGOLIA AND INDIA', 'Y', 157518.4, 2016, 'ST. LOUIS, MISSOURI', -90.1994042, 38.6270025), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((10, 'WITHDRAWN', 'LESSARD INTERNATIONAL LLC', 'CHIEF EXECUTIVES', 'PRESIDENT', 'Y', 154648.0, 2016, 'VIENNA, VIRGINIA', -77.2652604, 38.9012225), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((12, 'CERTIFIED-WITHDRAWN', 'DOW CORNING CORPORATION', 'CHIEF EXECUTIVES', 'VICE PRESIDENT AND CHIEF HUMAN RESOURCES OFFICER', 'Y', 163717.0, 2016, 'MIDLAND, MICHIGAN', -84.2472116, 43.6155825), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((15, 'CERTIFIED-WITHDRAWN', 'NEWMONT MINING CORPORATION', 'CHIEF EXECUTIVES', 'BOARD MEMBER', 'Y', 105914.0, 2016, 'GREENWOOD VILLAGE, COLORADO', -104.9508141, 39.6172101), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((16, 'CERTIFIED-WITHDRAWN', 'VRICON, INC.', 'CHIEF EXECUTIVES', 'CHIEF FINANCIAL OFFICER', 'Y', 153046.0, 2016, 'STERLING, VIRGINIA', -77.4291298, 39.0066993), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((17, 'CERTIFIED-WITHDRAWN', 'CARDIAC SCIENCE CORPORATION', 'FINANCIAL MANAGERS', 'VICE PRESIDENT OF FINANCE', 'Y', 90834.0, 2016, 'WAUKESHA, WISCONSIN', -88.2314813, 43.0116784), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((20, 'CERTIFIED', 'MCCHRYSTAL GROUP, LLC', 'CHIEF EXECUTIVES', 'PRESIDENT, NORTHEAST REGION', 'Y', 241842.0, 2016, 'ALEXANDRIA, VIRGINIA', -77.0469214, 38.8048355), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Row((21, 'CERTIFIED-WITHDRAWN', 'CUDDLE BARN, INC.', 'CHIEF EXECUTIVES', 'CHIEF OPERATING OFFICER (COO)', 'Y', 117998.0, 2016, 'COMMERCE, CALIFORNIA', -118.1597929, 34.0005691), {'Record': 0, 'CASE_STATUS': 1, 'EMPLOYER_NAME': 2, 'SOC_NAME': 3, 'JOB_TITLE': 4, 'FULL_TIME_POSITION': 5, 'PREVAILING_WAGE': 6, 'YEAR': 7, 'WORKSITE': 8, 'lon': 9, 'lat': 10})
Total records: 6004916